# -*- coding: utf-8 -*-

# Lista oficial de áreas y departamentos principales de la empresa
AREAS = [
    "PACKING",
    "SADEMA",
    "MANTENCION",
    "SERVICIOS GENERALES",
    "MERCADO INTERNO",
    "ENVASES",
    "RECEPCION",
    "BODEGA",
    "FRIGORIFICO",
    "INOCUIDAD",
    "SAG",
    "PREVENCION DE RIESGOS",
    "EXPORTADORA",
]

# Lista oficial de subáreas fijas de la empresa
SUBAREAS = [
    "BAÑOS PLANTA",
    "BODEGA",
    "CASINO",
    "FILTRO SANITARIO",
    "PACKING",
    "HAND PACK",
    "ADMINISTRACION",
    "LAVANDERIA",
    "PRODUCCION",
    "FRIGORIFICO",
    "TODAS LAS AREAS",
    "ENSAYO PACKING",
    "GUARDAROPA FILTRO",
    "UNITEC",
    "CASILLA ROPA-FILTRO",
    "ASEO",
    "CAMARA CEREZA",
    "OFICINAS ADMINISTRACION",
    "PCK CAROZOS",
    "PCK CEREZAS",
    "PORTERIA 2",
    "PORTERIA 1",
    "PLANTA TRATAMIENTO",
    "PLANTA RILES",
    "TALLER",
    "SERVICIOS GENERALES",
    "ENFERMERIA",
    "MANTENCION",
    "LINEA COMPAC 1",
    "SAG",
    "RECEPCION FRUTA",
    "OPERACIONES",
    "INOCUIDAD",
    "SEGURIDAD",
    "ENVASES",
    "MERCADO INTERNO",
    "CAMARA M.INTERNO",
    "DPTO. COMERCIAL",
    "DESAROLLO",
    "LOGISTICA",
    "DATOS E INFORMATICA",
    "GERENCIA",
    "CONTABILIDAD",
    "RR.HH",
    "ADQUISICIONES",
    "PREVENCION DE RIESGOS",
    "I + D",
    "BRC",
    "PALLETIZAJE",
]
